databases.admin_denodo_mpp.datasources.json.denodo_mpp_api.ROUTE.HTTP.PASSWORD=DC/drPB/vTsSxbumZ4DT9P0zqqJJxzqHJFO+XOzzWz9YNJmr1E6p+6SEDi9PXJE9z4iiIN93xYAQ4+tgU/Es2WcxjABJZQ46DYTwk6ovyfoTwhzxPD/V3d7h95CU+2d//1JvP6AckLY2i9XQrF/fjQ\=\=
databases.admin_denodo_mpp.datasources.json.denodo_mpp_api.ROUTE.HTTP.PASSWORD.ENCRYPTED=ENCRYPTED
databases.admin_denodo_mpp.datasources.json.denodo_mpp_api.ROUTE.HTTP.URL=https\://presto-denodo\:8443/v1/
databases.admin_denodo_mpp.datasources.json.denodo_mpp_api.ROUTE.HTTP.USER=presto
