databases.admin_denodo_mpp.datasources.jdbc.embedded_mpp.DATABASEURI=jdbc\:presto\://presto-denodo\:8443/hive/default?SSL\=true&protocols\=http11
databases.admin_denodo_mpp.datasources.jdbc.embedded_mpp.HDFS_URI=hdfs\://172.28.135.80\:9000/data/bulkload/
databases.admin_denodo_mpp.datasources.jdbc.embedded_mpp.USERNAME=presto
databases.admin_denodo_mpp.datasources.jdbc.embedded_mpp.USERPASSWORD=
databases.admin_denodo_mpp.datasources.jdbc.embedded_mpp.USERPASSWORD.ENCRYPTED=ENCRYPTED
databases.admin_denodo_mpp.datasources.jdbc.embedded_mpp.external_data.routes.route=hdfs\://172.28.135.80\:9000/data/tutorial/
